### ISSUE TITLE
mapview warning message

### ISSUE THREAD

**Issue by btitaro** [bcgov/bccamtrap#27]
> mapview(deployments, zcol = "sample_station_label")
Warning message:
In clean_columns(as.data.frame(obj), factorsAsCharacter) :
  Dropping column(s) timelapse_time of class(es) hms;difftime

**Comment by ateucher** [comment]
This can be safely ignored. It's because the `timelapse_time` column is a special `hms` (hours-minutes-second) data type, which mapview doesn't know what to do with, so it drops it. We have three options:

1. Ignore it, and/or drop that column yourself when you call mapview on it:

    ```r
    library(dplyr)
    library(mapview)
    
    mapview(select(deployments, -timelapse_time), zcol = "sample_station_label")
    ```
2. Import the timelapse_time column as a regular character type (more flexible but perhaps less useful)
3. Open an issue upstream in the `sf` package, where the warning is being thrown...

**Comment by btitaro** [comment]
Thanks Andy - Seems like option 1 might be easiest? We can discuss with others tomorrow as well though. Thanks again for the help yesterday!

Brian
________________________________

**Comment by ateucher** [comment]
Agreed, option 3 would be the best, I might pursue it later down the road...
